---
Name: staticsiteconnectorconfig
After: 'framework/*','cms/*'
---
StaticSiteRewriteLinksTask:
  log_file: '/var/tmp/failed-rewrite.log'
StaticSiteContentExtractor:
  log_file: '/var/tmp/import.log'